### ISSUE TITLE
Support for AndNot.

### ISSUE THREAD

**Issue by dvc94ch** [rust-lang/stdsimd#105]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_andnot_si128&expand=4906,3416,6170,338

**Comment by calebzulawski** [comment]
I'd have to check, but if you use the BitAnd and Not operators the compiler should produce this if it's in fact the fastest way to implement this.

Since this is an x86-specific instruction it doesn't really belong in stdsimd, but it's worth confirming that LLVM does produce this instruction (though if it doesn't, that's really an issue for LLVM)

**Comment by calebzulawski** [comment]
Just to follow up, as I suspected, LLVM will generate this instruction: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=2df7fe9609e4b448c2197bedd6ef2781

**Comment by dvc94ch** [comment]
Thanks for looking into this. I guess the issue is resolved.
